# Generated by Django 4.2.5 on 2023-12-12 20:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('post_img', models.ImageField(blank=True, upload_to='images/')),
                ('title', models.CharField(max_length=100)),
                ('authour', models.CharField(max_length=50)),
                ('content', models.TextField(max_length=10000)),
                ('hashtag', models.CharField(blank=True, max_length=10000)),
                ('created', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=50, unique=True)),
                ('firstname', models.CharField(max_length=70)),
                ('email', models.EmailField(max_length=254)),
                ('password', models.CharField(max_length=100)),
                ('profile_img', models.ImageField(default='images/images.png', upload_to='images/')),
                ('website', models.URLField(blank=True)),
                ('location', models.CharField(blank=True, max_length=120)),
                ('bio', models.TextField(blank=True, max_length=300)),
                ('tag', models.TextField(blank=True, max_length=300)),
                ('learning', models.TextField(blank=True, max_length=300)),
                ('available', models.TextField(blank=True, max_length=300)),
                ('skill', models.TextField(blank=True, max_length=300)),
                ('project', models.TextField(blank=True, max_length=300)),
                ('work', models.CharField(blank=True, max_length=200)),
                ('education', models.CharField(blank=True, max_length=200)),
            ],
        ),
    ]
