# Generated by Django 4.2.5 on 2023-11-02 02:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Blog', '0008_resturant'),
    ]

    operations = [
        migrations.CreateModel(
            name='Postimage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('post_img', models.ImageField(upload_to='images/')),
            ],
        ),
        migrations.DeleteModel(
            name='Resturant',
        ),
    ]
