# Generated by Django 4.2.5 on 2023-11-02 14:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Blog', '0009_postimage_delete_resturant'),
    ]

    operations = [
        migrations.AlterField(
            model_name='postimage',
            name='post_img',
            field=models.ImageField(blank=True, upload_to='images/'),
        ),
    ]
