# Generated by Django 4.2.5 on 2023-11-02 19:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Blog', '0010_alter_postimage_post_img'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Postimage',
        ),
        migrations.AddField(
            model_name='post',
            name='post_img',
            field=models.ImageField(blank=True, upload_to='images/'),
        ),
    ]
