# Generated by Django 4.2.5 on 2023-11-04 10:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Blog', '0011_delete_postimage_post_post_img'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='authour',
            field=models.CharField(max_length=50),
        ),
    ]
