# Generated by Django 4.2.5 on 2023-11-11 07:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Blog', '0018_alter_user_profile_img'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='available',
        ),
        migrations.RemoveField(
            model_name='user',
            name='bio',
        ),
        migrations.RemoveField(
            model_name='user',
            name='education',
        ),
        migrations.RemoveField(
            model_name='user',
            name='learning',
        ),
        migrations.RemoveField(
            model_name='user',
            name='location',
        ),
        migrations.RemoveField(
            model_name='user',
            name='project',
        ),
        migrations.RemoveField(
            model_name='user',
            name='skill',
        ),
        migrations.RemoveField(
            model_name='user',
            name='website',
        ),
        migrations.RemoveField(
            model_name='user',
            name='work',
        ),
    ]
