# Generated by Django 4.2.5 on 2023-11-11 08:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Blog', '0020_user_available_user_bio_user_education_user_learning_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='tag',
            field=models.TextField(blank=True, max_length=300),
        ),
    ]
