# Generated by Django 4.2.5 on 2023-11-15 20:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Blog', '0021_user_tag'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='User',
            new_name='Profile',
        ),
    ]
