# Generated by Django 4.2.5 on 2023-12-04 20:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Blog', '0023_alter_profile_firstname'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='hashtag',
            field=models.CharField(blank=True, choices=[('web developmet', '#web'), ('backend developmet', '#backend'), ('api', '#api'), ('frontend', '#frontend')], max_length=10000),
        ),
    ]
